##服务端口
server:
  port: 8089
spring:
  application:
    ###应用名
    name: webmvc-super-sql-mcp-server
  main:
    banner-mode: off
#    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/super-sql?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  ai:
    azure:
      openai:
        api-key: #Azure OpenAi 的key
        chat:
          options:
            deployment-name: #Azure OpenAI 的模型部署名称
        endpoint: #Azure OpenAI的请求地址 例如：https://your-domain.openai.azure.com/
        embedding:
          options:
            deployment-name: #Azure OpenAI 的embedding模型部署名称

    #  当使用 Ollama时，请配置以下参数
    #    ollama:
    #      base-url: http://localhost:11434
    #      chat:
    #        options:
    #          model: deepseek-r1:32b
    #          temperature: 0.7
    #      embedding:
    #        options:
    #          model: mxbai-embed-large
    #      init:
    #        pull-model-strategy: never
    #        embedding:
    #          additional-models:
    #            - mxbai-embed-large

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: super-sql
        initialize-schema: true
    #  重排序配置，可以上gitee Ai有免费体验 或者使用Xinference本地部署
    reranker:
      enabled: true
      model: Qwen3-Reranker-8B
      baseUrl: https://ai.gitee.com/v1/rerank #http://localhost:9997/v1/rerank
      api-key: xxxxxxxxxx

    mcp:
      server:
        name: webmvc-super-sql-mcp-server
        version: 1.0.0
        stdio: false
        type: ASYNC
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

super-sql:
  init-train: true
  scope: ALONE
  schemas:
    - schema: dtp


mybatis-plus:
  global-config:
    banner: off